version: '3'
services:
  firstService:
    image: ghost:1-alpine
    environment:
    database_client: mysql
    database_connection_host: db
    database_connection_user: root
    database_connection_password: umasenha123
    database_connection_database: ghost
    depends_on:
      - db #espera container subir
    ports:
      - 2368:2368
    networks:
      - my-network
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: umasenha123
    volumes: var/lib/mysql
    networks:
      - my-network
## docker-compose up -d
